import { DateLocalization } from "./type";

export const multilingual: Record<string, DateLocalization> = {
  vi: {
    L: ["Chủ nhật", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
    l: ["chủ nhật", "thứ 2", "thứ 3", "thứ 4", "thứ 5", "thứ 6", "thứ 7"],
    tK: "lúc",
    TK: "Lúc",
    eM: [
      "tháng 1",
      "tháng 2",
      "tháng 3",
      "tháng 4",
      "tháng 5",
      "tháng 6",
      "tháng 7",
      "tháng 8",
      "tháng 9",
      "tháng 10",
      "tháng 11",
      "tháng 12",
    ],
    EM: [
      "Tháng 1",
      "Tháng 2",
      "Tháng 3",
      "Tháng 4",
      "Tháng 5",
      "Tháng 6",
      "Tháng 7",
      "Tháng 8",
      "Tháng 9",
      "Tháng 10",
      "Tháng 11",
      "Tháng 12",
    ],
    tY: "năm",
    TY: "Năm",
    vx: "Vừa xong",
    vp: "Vài giây trước",
    vs: "Sắp tới",
    vv: "trước",
    xx: "sau",
    tD: "ngày",
    TD: "Ngày",
    tM: "tháng",
    TM: "Tháng",
    tH: "giờ",
    TH: "Giờ",
    tI: "phút",
    TI: "Phút",
    tS: "giây",
    TS: "Giây",
  },
  en: {
    L: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    l: [
      "sunday",
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
    ],
    tK: "at",
    TK: "At",
    eM: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    EM: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    tY: "year",
    TY: "Year",
    vx: "Just now",
    vp: "A few seconds ago",
    vs: "Coming soon",
    vv: "ago",
    xx: "from now",
    tD: "day",
    TD: "Day",
    tM: "month",
    TM: "Month",
    tH: "hour",
    TH: "Hour",
    tI: "minute",
    TI: "Minute",
    tS: "second",
    TS: "Second",
  },
  ja: {
    L: ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"],
    l: [
      "にちようび",
      "げつようび",
      "かようび",
      "すいようび",
      "もくようび",
      "きんようび",
      "どようび",
    ],
    tK: "に",
    TK: "ニ",
    eM: [
      "1月",
      "2月",
      "3月",
      "4月",
      "5月",
      "6月",
      "7月",
      "8月",
      "9月",
      "10月",
      "11月",
      "12月",
    ],
    EM: [
      "1月",
      "2月",
      "3月",
      "4月",
      "5月",
      "6月",
      "7月",
      "8月",
      "9月",
      "10月",
      "11月",
      "12月",
    ],
    tY: "年",
    TY: "年",
    vx: "たった今",
    vp: "数秒前",
    vs: "もうすぐ",
    vv: "前",
    xx: "後",
    tD: "日",
    TD: "日",
    tM: "月",
    TM: "月",
    tH: "時",
    TH: "時",
    tI: "分",
    TI: "分",
    tS: "秒",
    TS: "秒",
  },
  lo: {
    L: [
      "ວັນອາທິດ",
      "ວັນຈັນ",
      "ວັນອັງຄານ",
      "ວັນພຸດ",
      "ວັນພະຫັດ",
      "ວັນສຸກ",
      "ວັນເສົາ",
    ],
    l: [
      "ວັນອາທິດ",
      "ວັນຈັນ",
      "ວັນອັງຄານ",
      "ວັນພຸດ",
      "ວັນພະຫັດ",
      "ວັນສຸກ",
      "ວັນເສົາ",
    ],
    tK: "ເວລາ",
    TK: "ເວລາ",
    eM: [
      "ມັງກອນ",
      "ກຸມພາ",
      "ມີນາ",
      "ເມສາ",
      "ພຶດສະພາ",
      "ມິຖຸນາ",
      "ກໍລະກົດ",
      "ສິງຫາ",
      "ກັນຍາ",
      "ຕຸລາ",
      "ພະຈິກ",
      "ທັນວາ",
    ],
    EM: [
      "ມັງກອນ",
      "ກຸມພາ",
      "ມີນາ",
      "ເມສາ",
      "ພຶດສະພາ",
      "ມິຖຸນາ",
      "ກໍລະກົດ",
      "ສິງຫາ",
      "ກັນຍາ",
      "ຕຸລາ",
      "ພະຈິກ",
      "ທັນວາ",
    ],
    tY: "ປີ",
    TY: "ປີ",
    vx: "ເພິ່ງແລ້ວ",
    vp: "ບໍ່ດົນມານີ້",
    vs: "ຈະມາເຖິງ",
    vv: "ຜ່ານມາ",
    xx: "ຫຼັງຈາກນີ້",
    tD: "ວັນ",
    TD: "ວັນ",
    tM: "ເດືອນ",
    TM: "ເດືອນ",
    tH: "ຊົ່ວໂມງ",
    TH: "ຊົ່ວໂມງ",
    tI: "ນາທີ",
    TI: "ນາທີ",
    tS: "ວິນາທີ",
    TS: "ວິນາທີ",
  },
  zh: {
    L: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
    l: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
    tK: "在",
    TK: "在",
    eM: [
      "一月",
      "二月",
      "三月",
      "四月",
      "五月",
      "六月",
      "七月",
      "八月",
      "九月",
      "十月",
      "十一月",
      "十二月",
    ],
    EM: [
      "一月",
      "二月",
      "三月",
      "四月",
      "五月",
      "六月",
      "七月",
      "八月",
      "九月",
      "十月",
      "十一月",
      "十二月",
    ],
    tY: "年",
    TY: "年",
    vx: "刚刚",
    vp: "几秒前",
    vs: "即将到来",
    vv: "之前",
    xx: "之后",
    tD: "天",
    TD: "天",
    tM: "月",
    TM: "月",
    tH: "小时",
    TH: "小时",
    tI: "分钟",
    TI: "分钟",
    tS: "秒",
    TS: "秒",
  },
  fr: {
    L: [
      "Dimanche",
      "Lundi",
      "Mardi",
      "Mercredi",
      "Jeudi",
      "Vendredi",
      "Samedi",
    ],
    l: [
      "dimanche",
      "lundi",
      "mardi",
      "mercredi",
      "jeudi",
      "vendredi",
      "samedi",
    ],
    tK: "à",
    TK: "À",
    eM: [
      "Janvier",
      "Février",
      "Mars",
      "Avril",
      "Mai",
      "Juin",
      "Juillet",
      "Août",
      "Septembre",
      "Octobre",
      "Novembre",
      "Décembre",
    ],
    EM: [
      "Janvier",
      "Février",
      "Mars",
      "Avril",
      "Mai",
      "Juin",
      "Juillet",
      "Août",
      "Septembre",
      "Octobre",
      "Novembre",
      "Décembre",
    ],
    tY: "année",
    TY: "Année",
    vx: "À l'instant",
    vp: "Il y a quelques secondes",
    vs: "Bientôt",
    vv: "il y a",
    xx: "dans",
    tD: "jour",
    TD: "Jour",
    tM: "mois",
    TM: "Mois",
    tH: "heure",
    TH: "Heure",
    tI: "minute",
    TI: "Minute",
    tS: "seconde",
    TS: "Seconde",
  },
};
