import { DateLocalization } from "./type";

export const multilingual: Record<string, DateLocalization> = {
  vi: {
    L: ["Chủ nhật", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
    l: ["chủ nhật", "thứ 2", "thứ 3", "thứ 4", "thứ 5", "thứ 6", "thứ 7"],
    tK: "lúc",
    TK: "Lúc",
    eM: [
      "tháng 1",
      "tháng 2",
      "tháng 3",
      "tháng 4",
      "tháng 5",
      "tháng 6",
      "tháng 7",
      "tháng 8",
      "tháng 9",
      "tháng 10",
      "tháng 11",
      "tháng 12",
    ],
    EM: [
      "Tháng 1",
      "Tháng 2",
      "Tháng 3",
      "Tháng 4",
      "Tháng 5",
      "Tháng 6",
      "Tháng 7",
      "Tháng 8",
      "Tháng 9",
      "Tháng 10",
      "Tháng 11",
      "Tháng 12",
    ],
    tY: "năm",
    TY: "Năm",
    vx: "Vừa xong",
    vp: "Vài giây trước",
    vs: "Sắp tới",
    vv: "trước",
    xx: "sau",
    tD: "ngày",
    TD: "Ngày",
    tM: "tháng",
    TM: "Tháng",
    tH: "giờ",
    TH: "Giờ",
    tI: "phút",
    TI: "Phút",
    tS: "giây",
    TS: "Giây",
  },
};
